### ISSUE TITLE
Please Include All Private IP's in "SECURITY SETTINGS"

### ISSUE THREAD

**Issue by tjharman** [MatthewVance/unbound-docker#10]
Hi,

I have just installed this image and gone to use it.  But I can't do recursive lookups from my LAN.  Testing dig @localhost works fine.

I have examined the unbound.conf and found the following:

```
    ###########################################################################
    # SECURITY SETTINGS
    ###########################################################################
    # Only give access to recursion clients from LAN IPs
    access-control: 127.0.0.1/32 allow
    access-control: 192.168.1.1/24 allow
    access-control: 172.16.0.0/12 allow
    access-control: 10.0.0.0/8 allow
```

Could you please update the 192.168 line there? 
This should be 192.168.0.0/16 shouldn't it, as that's the range of "Internal" IP's there.  You have the correct mask for the 10.X subnet.

My LAN is 192.168.0.0/24 so that's why I can't resolve against it.

Thanks!

**Comment by MatthewVance** [comment]
Good catch. I can fix later or you can submit a pull request. In the
interim, I suggest using a custom config file. See
https://github.com/MatthewVance/unbound-docker/blob/master/README.md#use-a-customized-unbound-configuration

**Comment by tjharman** [comment]
Thanks!  My git skills are sorely lacking so I won't attempt a pull request I'm sorry.

Another range you may want to consider adding is 

100.64.0.0/10

Which is described in RFC 6598 as space for ISPs doing large scale NAT (cg-nat)

Thanks very much!

**Comment by MatthewVance** [comment]
The 100.64 range is an interesting one. While technically private, I'm not
sure how useful it'll be to the average user since it's mainly targeted for
ISP usage (cg-nat) per
https://en.wikipedia.org/wiki/IPv4_shared_address_space.

My initial thought is the people likely to need this probably won't be
using default settings and will have the skills needed to adjust the config
manually. It also ever so slightly lowers default security controls (i.e.,
other customers of the same ISP could potentially do recursive lookups
against your server from their LAN).

Let me know if I'm missing a compelling use case to also include this IPv4
shared address range when correcting the other CIDR masks.

**Comment by tjharman** [comment]
No, you are completely right.  The average user is never going to encounter this.  I'm not sure what I was thinking really.

I retract my comment, it shouldn't be included.  Just updating the 192 line to 192.168.0.0/16 is all that's needed.

I have moved to using my own local copy of unbound.conf as it's so easy to do anyway (thanks) so have modified things as I need them.

Appreciate the prompt replies, thanks again.

**Comment by MatthewVance** [comment]
Glad to help and thanks for catching and reporting my mistake.
