### ISSUE TITLE
/dev/null - permission denied

### ISSUE THREAD

**Issue by ChristianWieck1977** [MatthewVance/unbound-docker#101]
unbound[1:0] error: Could not open logfile /dev/null: Permission denied
unbound[1:0] info: start of service (unbound 1.16.0).

**Comment by mxmartins** [comment]
Probably need to take a look at your docker-compose file along with the unbound.conf to really see what is going on.
I have no such problem...

**Comment by ChristianWieck1977** [comment]
Hi,
thanks for our quick response - find attached my conf file
thanks in advance
Christian

Am Mi., 15. Juni 2022 um 09:24 Uhr schrieb mxmartins <
***@***.***>:

**Comment by mxmartins** [comment]
And how did you create the container?

**Comment by MatthewVance** [comment]
The default logfile won't be accessible if you try to view it and won't show anything useful if you could. /dev/null is a special file type on Linux (see https://linuxhint.com/what_is_dev_null/). The default config uses it for privacy reasons. The simple fix is to use a custom config and set the logfile to a different path with the right permissions.

Are you by chance running this on a synology nas? I ask because of this issue report: https://github.com/MatthewVance/unbound-docker/issues/98

**Comment by MatthewVance** [comment]
Closing due to no response. Feel free to re-open if needed.

**Comment by nillebor** [comment]
Add any other context about the problem here.

We have 2 Synology diskstation with adguard and unbound. Both run separately in different networks.

the first Diskstation runs perfectly - no error in the log.

the second distation always comes with the same settings the error: `unbound[1:0] error: Could not open logfile /dev/null: Permission denied`

I don't understand where the difference should be. with the exception of the Diskstation, everything is the same from the OS to the applications. No directory is mapped locally.

i have already found the errors here but that doesn't really help me.
