### ISSUE TITLE
Cant access a specific domain with unbound as dns server.

### ISSUE THREAD

**Issue by ektorasdj** [MatthewVance/unbound-docker#153]
Hello, i am not able to connect to https://www.sas.com/ when using your image with the default configuration.
I am able to connect with the setting "val-permissive-mode: yes" but i am not really sure if its ok using this setting.
I am also able to connect by using crazymax's image of unbound but i want to use yours.
Can you help me?

Thank you for this great tool!

**Comment by MatthewVance** [comment]
My guess is that domain has a DNSSEC issue. I get a SERVFAIL when running dig on that domain. I believe `val-permissive-mod` tells Unbound to ignore some DNSSEC related issues.

`val-permissive-mod` is not a setting that is explicitly configured when [unbound.sh](https://github.com/MatthewVance/unbound-docker/blob/master/1.19.0/data/unbound.sh) builds the default config for this image. That means the image falls back to Unbound's default which is no per https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html. 

The decription of that setting is:

> Instruct the validator to mark bogus messages as indeterminate. The security checks are performed, but if the result is bogus (failed security), the reply is not withheld from the client with SERVFAIL as usual. The client receives the bogus data. For messages that are found to be secure the AD bit is set in replies. Also logging is performed as for full validation.

Setting it to yes is a bit of a security issue because the client may get bad DNS data in some cases. SERVFAIL can occur for a number of reasons. This [article](https://blog.cloudflare.com/unwrap-the-servfail/) has a good summary of potential SERVFAIL reasons.
