### ISSUE TITLE
"dockerfile" healthckeck in line 155

### ISSUE THREAD

**Issue by matthiasklabe** [MatthewVance/unbound-docker#156]
Hello Matthew,

I'm using the latest image of this project and additional portainer in the latest version. 
If you go into the respective Area where you can see all containers and volumes a.s.o. you have also a section call ed Events

Here I get a lot of entries which still floating logs file from portainer.
I mean is there any other option to have such "heartbeat" in place without getting this entries.
Yes you are right, issue is with portainer. But I like that tool ;-)

![P1](https://github.com/MatthewVance/unbound-docker/assets/154374589/9f4cbb05-fcaf-458a-8ac9-e02af7774d41)

Perhaps you have an idea which helps to reduce those entries.

BR & Thanks for your effort

Matthias Klabe

**Comment by MatthewVance** [comment]
Hi Matthias, I've never used portainer so I'm not familar with what options it may have natively to reduce such entries. You can reduce the entries by adjusting the healthcheck settings using healthcheck options (increase the interval so that it checks less often). You could also use the --no-healthcheck flag to override the default and not have any checks. To be fair, healthcheck is of limited value with the default setup given the issue described at https://github.com/MatthewVance/unbound-docker/issues/112.

**Comment by matthiasklabe** [comment]
Hi Matthew, Thanks for the quick reply. Is there any option to add an environment variable in the docker-compose, because I'm not creating the image by myself. I started with docker and all these new topics around half a year ago. For sure I don't want waste your time ;-)

**Comment by MatthewVance** [comment]
Here is the link to Docker docs about using Healthcheck in a compose flie: https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck.

**Comment by matthiasklabe** [comment]
Thanks for your Support, you can close this issue.
