### ISSUE TITLE
Add root hints

### ISSUE THREAD

**Issue by bruvv** [MatthewVance/unbound-docker#28]
In the pihole docummention they recommend getting root hints for faster caching.
https://docs.pi-hole.net/guides/unbound/#setting-up-pi-hole-as-a-recursive-dns-server-solution

Perhaps add this to the new version as well?

**Comment by MatthewVance** [comment]
The unbound image itself does not provide a root.hints file. With the
default config, this image is designed to forward queries to an external
resolving DNS server over TLS rather than act as a recursive DNS server.
While the image can work as a recursive DNS server, it requires you to
update the configuration accordingly (and provide any necessary files).

That being said, by default a list of builtin root hints is used by
Unbound. Providing your own file is supported for Unbound in the event you
need to provide a more up-to-date list. If the package stays updated, that
shouldn't be necessary.

https://wiki.archlinux.org/index.php/unbound#Root_hints

https://nlnetlabs.nl/documentation/unbound/unbound-anchor/

**Comment by bruvv** [comment]
Awesome thanks for the links and the information, very useful!
