### ISSUE TITLE
Need a little help building own version of unbound

### ISSUE THREAD

**Issue by marcoheijkoop** [MatthewVance/unbound-docker#39]
Hi Matthew

I'm using youre Unbound for my Synology from this Github https://github.com/chriscrowe/docker-pihole-unbound and it works great.

In only want to use the Quad9 version. The Github from Chris says this.
"If you want to change any of this Unbound config then you can fork MatthewVance's unbound-docker repo and modify his unbound.sh file."

So i did and now i have https://github.com/marcoheijkoop/unbound-docker.

But i'm a little but stuck now ;-)
I have this https://hub.docker.com/repository/docker/marcoheijkoop/unbound
And now i'm totaly lost :-(
Can you get me any further or point me in the right direction?

Best Regards,
Marco

**Comment by MatthewVance** [comment]
Hi Marco,

I'm sorry you ran into trouble. The edits you made to the [unbound.sh file in your GitHub repo](https://github.com/marcoheijkoop/unbound-docker/blob/master/1.10.0/unbound.sh) look right to me. 

Can you share more details about the problem you're having? Are you seeing an error or not know what to do next? I have not yet used PiHole (still need to give it a try), but I would think you'd update the [Docker Compose file from the Pi-Hole repo](https://github.com/chriscrowe/docker-pihole-unbound/blob/master/docker-compose.yaml#L35) to point to your custom image rather than mine. 

Re-building the container is one way to achieve what you're after. Another way may be to run my image and mount a custom Unbound config file as described [here](https://github.com/MatthewVance/unbound-docker#use-a-customized-unbound-configuration). As with the above, you'd modify the Pi-Hole docker-compose file accordingly. In other words, you would need to translate the example docker run command in the read me to docker-compose format. 

If it helps, [this config file](https://gist.github.com/MatthewVance/4842e0ad8305a09e87b95787e656243d) is pretty close to what is auto-built by the shell script. The main difference is the performance settings won't be auto-optimized for the machine running the container.

Thanks,
Matt

**Comment by MatthewVance** [comment]
It's not a big deal, but you may also want to revise the Healthcheck in the [forked Dockerfile](https://github.com/marcoheijkoop/unbound-docker/blob/108fe3944bd6b5164b3a3d470fc47548d32c6d45/1.10.0/Dockerfile#L141) to point to Quad9 rather than Cloudflare.

**Comment by living-mobile** [comment]
> Can you share more details about the problem you're having? Are you seeing an error or not know what to do next? I have not yet used PiHole (still need to give it a try), but I would think you'd update the [Docker Compose file from the Pi-Hole repo](https://github.com/chriscrowe/docker-pihole-unbound/blob/master/docker-compose.yaml#L35) to point to your custom image rather than mine.
> 
I'm having problems with building the container. I already installed Docker Desktop so i think i need to go in that direction. I already changed the Docker Compose file and there i had some errors because there wasn't a container. So im learning on the job ;-)

> Re-building the container is one way to achieve what you're after. Another way may be to run my image and mount a custom Unbound config file as described [here](https://github.com/MatthewVance/unbound-docker#use-a-customized-unbound-configuration).
> 
I'm trying to rebuild because changing the conf file on the Synology was difficult. And i think rebuilding is the best option. But maybe i'm wrong. Hahaha

**Comment by marcoheijkoop** [comment]
> Can you share more details about the problem you're having? Are you seeing an error or not know what to do next? I have not yet used PiHole (still need to give it a try), but I would think you'd update the [Docker Compose file from the Pi-Hole repo](https://github.com/chriscrowe/docker-pihole-unbound/blob/master/docker-compose.yaml#L35) to point to your custom image rather than mine.
> 
I'm having problems with building the container. I already installed Docker Desktop so i think i need to go in that direction. I already changed the Docker Compose file and there i had some errors because there wasn't a container. So im learning on the job ;-)

> Re-building the container is one way to achieve what you're after. Another way may be to run my image and mount a custom Unbound config file as described [here](https://github.com/MatthewVance/unbound-docker#use-a-customized-unbound-configuration).
> 
I'm trying to rebuild because changing the conf file on the Synology was difficult. And i think rebuilding is the best option. But maybe i'm wrong. Hahaha

**Comment by marcoheijkoop** [comment]
Lol. Pressed the wrong button

**Comment by marcoheijkoop** [comment]
Hi Matthew,

Re-building finaly worked for me. In still need some tweaks because mine version is called version 1.0 instead of latetst. So i need that to firgure out somehow.

I closing the issue

**Comment by MatthewVance** [comment]
You can add a tag to the built image.

Find the image hash by running:
docker images

Then run:
docker <hash> tag name/unbound:latest

**Comment by MatthewVance** [comment]
Glad you got it working. If it helps more, I just merged a pull request from @Sispheor that makes modifying the forwarder even easier. See https://github.com/MatthewVance/unbound-docker/pull/41 for details.
