### ISSUE TITLE
Error Unbound Windows 64 20h2

### ISSUE THREAD

**Issue by Marcosdw** [MatthewVance/unbound-docker#64]
Hello, 

Error logs windows

C:\Program Files\Unbound\unbound.exe:0] error: udp connect failed: No error for 2001:dc3::35 port 53

Thank you for giving me a solution

Sorry, I use a French / English online translator 

unbound_setup_1.13.1

**Comment by MatthewVance** [comment]
Hello,

This is related to https://github.com/MatthewVance/unbound-docker/issues/55. That issue is actually related to an upstream Unbound issue (see https://github.com/NLnetLabs/unbound/issues/364). I am not aware of a fix for this Docker issue until the upstream version release resolves the underlying problem. For now, the container will work despite the IPv6 related error in the log.

I hope this helps. Do not worry about using a translator. I understood the issue you reported. I hope my reply is understandable.
