### ISSUE TITLE
Radio via TuneIn not working from Homepod

### ISSUE THREAD

**Issue by timwegenerDE** [MatthewVance/unbound-docker#70]
Hi there,

I‘m new to unbound (and most of the DNS-Networkstuff). I tried using unbound for my pihole setup. So far everything is working as excpected. Only the radio streaming on my Homepod is not working. The Stream comes via Apple Music over TuneIn(.com?). The stream is working on other devices via Apple Music without any problem. Sounds weird to me.

When starting the container I get some error messages (what COULD be associated):
`[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:7fe::53 port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:dc3::35 port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:503:ba3e::2:30 port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:7fe::53 port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:2::c port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:12::d0d port 53

[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53
`

I read some similar issues here with the above messages, but I haven’t found anything that helped resolving them.

Any ideas? I‘m lost 😩 

Kind regards,
Tim

**Comment by MatthewVance** [comment]
Hello Tim,

That is an odd one. 

The `[1626508052] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53` error should be entirely unrelated. Best I can tell, it's because Unbound expects IPv6 support, but Docker containers do not support IPv6 by default. Short of setting up IPv6 on Docker, I do not know of a way to solve it. I think the root cause will have to be patched during a new release of Unbound. The good news is that error should not cause any problems because everything should still work with just IPv4 (Unbound will still resolve IPv6). 

As for your particular issue, two potential causes come to mind. 

1. The first is Pi-Hole could be blocking TuneIn or a related domain. This is the most likely cause. If this is the case, you should be able to unblock that domain (or any related ones being called, you'll need to check the logs). This may help: https://www.reddit.com/r/pihole/comments/e462hm/unable_to_use_spotify_with_pihole_yes_its/
2. The second is your upstream DNS server (if you're forwarding rather than recursively resolving) could be blocking those domains. If you're using something like Cloudflare DNS (regular version) or Google DNS, they should not be blocking anything. However, some DNS providers like CleanBrowsing or Quad9 do some filtering. The default forwarder with this image is Cloudflare (see https://github.com/MatthewVance/unbound-docker/blob/master/1.13.1/data/opt/unbound/etc/unbound/forward-records.conf#L10).

To confirm it's not this Docker image causing the issue, you can temporarily run Unbound by itself without Pi-hole. You'll need to stop your existing container and run a new one using the README instructions. If streaming works, that narrows down the issue to Pi-hole or less likely any of your customized Unbound settings.

The stream is most likely working on other devices because those other devices are probably using a different DNS server. Unless you've configured your router to assign your Docker DNS service IP as the DNS server for all devices on your network using DHCP or you've manually changed the DNS server on all your other devices, they are likely not using Unbound / Pi-Hole.

Thanks,

**Comment by timwegenerDE** [comment]
Thanks for your time!

Using my Pi Hole setup without unbound, but with Cloudflare as upstream (1.1.1.1 and 1.0.0.1) everything is working. Also I have not configured a specific upstream dns for the unbound container.

I‘m using DHCP for publishing the Pi Hole as DNS, so all tested devices should use the Pi Hole as DNS.

Pi Hole and unbound container are running on the same device so I will try the following:
- Stopping the Pi Hole Container
- Configure the unbound container for using port 53. We should see if it‘s Pi Hole related.

**Comment by timwegenerDE** [comment]
Ok I tried using unbound directly and it‘s working. But suddenly it‘s also working with Pi Hole. So I re-checked everything.

The last time when it wasn‘t working I had disabled DNSSEC in Pi Hole because I read somewhere it‘s recomended to disable it when using unbound. This time I forget to disable it and: Everything is working…

I also disabled caching for Pi Hole before, but with no luck. As far as I know caching is also disabled when using DNSSEC. So maybe it‘s something with the cache and not DNSSEC itself…?

Is it a problem using unbound with Pi Hole where DNSSEC is enabled on Pi Hole?

**Comment by timwegenerDE** [comment]
It‘s getting weird. Now my macMini doesn‘t do any name resolution. If I‘m using Pi Hole without unbound it‘s working and when I use unbound without Pi Hole it‘s also working.

I can see the query to Pi Hole and it says forwarded to unbound. But no answer to the client.

**Comment by timwegenerDE** [comment]
I‘m now testing Adguard Home with unbound - so far without any problems.

So I‘m not sure what‘s that weird problem with Pi Hole is. For now I will close this issue. If someone has a simillar issue with Pi Hole it would be great to mention it here. I would consider going back to Pi Hole if I can solve the problem.

**Comment by MatthewVance** [comment]
Thanks for reporting back and closing this. This confirms my initial suspicion that this was a Pi-hole issue rather than something related to Unbound.
